server:
  port: 8081 # Java 机器自己的 Web 端口

xxl:
  job:
    admin:
      # 【核心灵魂】：优先读取 K8s 注入的环境变量，如果没有则默认连本地 Go 引擎
      addresses: ${XXL_JOB_ADMIN_ADDRESSES:http://127.0.0.1:8080} 
    executor:
      appname: loan-service # 业务组名，必须与 Go 引擎后台配置的一致
      port: 9999 # XXL-Job 内置 Netty 监听端口，用于接收 Go 发来的任务触发指令
      logpath: ./logs/xxl-job/jobhandler
